### ISSUE TITLE
Understanding Dumb data

### ISSUE THREAD

**Issue by mamounelkhettar** [git-afsantos/ros_data#1]
Hello,

I would like to understand the data in the dumb folder.
I want to do an analysis of the relationships between the different nodes and topics and their recurrences.
Could you tell me exactly where the data in the txt files in dumb comes from and how to interpret it ?

Thank You.

**Comment by git-afsantos** [comment]
Hi. The data in `dump` is just a print of all the Python objects I had within the tools at the time. Basically:

```python
for all pub in publishers:
    print pub
```

**pub_data.txt:** contains all the publishers the tools found.
**sub_data.txt:** contains all the subscribers the tools found.
**rpc_data.txt:** contains all the services the tools found.
**other_data.txt:** contains parameters and spin rates.

This is the same data that is contained in the other CSV files, only in a different format.

## Publishers

```python
AdvertiseTuple(topic='/torso/joint_group_velocity_controller/command', queue_size=1, message_type='std_msgs::Float64MultiArray', nesting=0, variable='command_pub_', function='KinematicExtensionTorso', line=99, overload='advertise(string topic, uint32_t queue_size, bool latch)', latch=None, param_topic=False, param_queue=False)
```

- `topic`, `queue_size`, `message_type` and `latch` are self-explanatory from the ROS API.
- `nesting` tells you the control flow nesting level within the function. Zero means no control flow around the `advertise` call, 1 means an `if` or a `for`, etc., and so on.
- `variable` tells you the C++ variable that the publisher is assigned to, e.g., `x = advertise(...)`.
- `function` tells you the function that contains the call to `advertise`, e.g., `main`.
- `line` tells you the line number in the source file.
- `overload` tells you which overload of the `advertise` function is being called from the [ROS API](http://docs.ros.org/kinetic/api/roscpp/html/classros_1_1NodeHandle.html).
- `param_topic` tells you whether the topic name comes from a ROS parameter.
- `param_queue` tells you whether the queue size comes from a ROS parameter.

## Subscribers

```python
SubscribeTuple(topic='/torso/joint_states', queue_size=1, callback='jointstateCallback', message_type='sensor_msgs::JointState', nesting=0, variable='joint_state_sub_', function='KinematicExtensionTorso', line=98, overload='subscribe(string topic, uint32_t queue_size, void method(M), T *obj, TransportHints)', transport_hints=False, param_topic=False, param_queue=False)
```

Mostly the same as above.

- `callback` tells you the callback function given to the `subscribe` call.
- `transport_hints` tells you whether the `subscribe` call was given `TransportHints`.

## Service

```python
AdvertiseServiceTuple(topic='change_state', callback='changeModeSrvCb', message_type='turtlebot_msgs::SetFollowState::Request &, turtlebot_msgs::SetFollowState::Response', nesting=0, variable='switch_srv_', function='onInit', line=115, overload='advertiseService(string service, bool method(MReq, MRes), T *obj)', service_event=False, param_topic=False)
```

Same as above.

## Service Client

```python
ServiceClientTuple(topic='robotiq_force_torque_sensor_acc', message_type='robotiq_force_torque_sensor::struct robotiq_force_torque_sensor::sensor_accessor', nesting=0, variable='client', function='main', line=71, overload='serviceClient(string service, bool persistent, M_string)', param_topic=False)
```

Same as above.

## Parameter

```python
ParamTuple(param='battery_max_voltage', variable='max_voltage', default=True, param_type='double', function='cob_voltage_control_ros', line=58)
```

- `param` and `param_type` should be self-explanatory.
- `default` tells you whether the parameter was given a default value.

## Spin Rate

```python
SpinRateTuple(rate=[ros::Time] #now, variable='period', function='updateIntegration', line=84, param_rate=False, is_duration=True, wall=False)
```

- `rate` tells you the spin rate, frequency or duration.
- `param_rate` tells you whether it comes from parameters.
- `is_duration` tells you whether it is a `Duration` or a `Rate`.
- `wall` tells you whether it uses wall time or ROS time.

Weird stuff like `[ros::Time] #now` are object prints from [bonsai](https://github.com/git-afsantos/bonsai/) objects, in whatever prototype version I had at the time.

**Comment by mamounelkhettar** [comment]
Thank You very much!
